"""initial schema

Revision ID: 4d3895ad10bf
Revises: 
Create Date: 2026-06-23 18:13:46.162743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d3895ad10bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_type', sa.Enum('residential', 'commercial', name='customertype'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('mobile', sa.String(length=30), nullable=True),
    sa.Column('billing_street', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=50), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('quickbooks_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quickbooks_id')
    )
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('owner', 'office', 'tech', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service_locations',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('access_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('job_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('estimate', 'quoted', 'approved', 'scheduled', 'in_progress', 'complete', 'invoiced', 'paid', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('vertical', sa.Enum('hvac', 'electrical', 'pipefitting', name='jobvertical'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('service_location_id', sa.UUID(), nullable=False),
    sa.Column('assigned_tech_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope_of_work', sa.Text(), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_window', sa.String(length=50), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('material_markup', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quote_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('internal_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quote_number', sa.String(length=50), nullable=True),
    sa.Column('quote_sent_at', sa.DateTime(), nullable=True),
    sa.Column('quote_approved_at', sa.DateTime(), nullable=True),
    sa.Column('quote_valid_days', sa.Integer(), nullable=True),
    sa.Column('close_note', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_tech_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['service_location_id'], ['service_locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_table('change_orders',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('co_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('additional_items', sa.Text(), nullable=True),
    sa.Column('additional_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='changeorderstatus'), nullable=True),
    sa.Column('approval_token', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_notes',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('client_uuid', sa.String(length=100), nullable=True),
    sa.Column('captured_at', sa.String(length=50), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('invoices',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'sent', 'paid', 'overdue', name='invoicestatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_lines_verified', sa.Boolean(), nullable=True),
    sa.Column('review_hours_verified', sa.Boolean(), nullable=True),
    sa.Column('review_co_verified', sa.Boolean(), nullable=True),
    sa.Column('review_nocharge_verified', sa.Boolean(), nullable=True),
    sa.Column('review_total_verified', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('quickbooks_invoice_id', sa.String(length=100), nullable=True),
    sa.Column('quickbooks_synced_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_7_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_14_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_30_sent', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_photos',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=False),
    sa.Column('photo_type', sa.Enum('equipment', 'site', 'completed', 'change_order', name='phototype'), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('ai_analyzed', sa.Boolean(), nullable=True),
    sa.Column('client_uuid', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('job_supply_items',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.Enum('photo', 'dictation', 'inferred', 'manual', name='supplysource'), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('po_sent', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('van_inventory',
    sa.Column('tech_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity_on_hand', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restock_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restock_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restock_needed', sa.Boolean(), nullable=True),
    sa.Column('last_used_job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_used_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tech_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('van_inventory')
    op.drop_table('job_supply_items')
    op.drop_table('job_photos')
    op.drop_table('invoices')
    op.drop_table('field_notes')
    op.drop_table('change_orders')
    op.drop_table('jobs')
    op.drop_table('service_locations')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
